# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8d9cd745bf360a3d2a859d4a2ba2368cadb7adb9d06ed7b444166f598dcd53593e6e5276a4603c5358066a1aa18a390bcd88bb5b693ebf8099424f5a75484d8

test:
  secret_key_base: b0b135cdb017da15395125e12508c7848040a9675801037b4b9394e1af5ef681171fc17d718f387ef6f35012ea842c79a9b5083dc23b23ee4cce45231266a144

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: osjonerij03j0tj094jh3ojgij2ojgo9ujw0ojdvisut403jifjeiojroj3<F3>9utgo9jwivjwovjbi30y0wjsibnikj0
